### ISSUE TITLE
resolver error: Host not found with dispatch_http_call

### ISSUE THREAD

**Issue by sluramod** [Kong/ngx_wasm_module#573]
Environment: kong 3.6.1

Using Rust Wasm SDK

kong config:

```
_format_version: "1.1"


upstreams:
  - name: test_api
    algorithm: round-robin
    id: 31314F2A-F6BE-4ACA-B1D0-D9C8ED3895EC

targets:
  - target: "host.docker.internal:8080"
    upstream: { id: "31314F2A-F6BE-4ACA-B1D0-D9C8ED3895EC" }
    id: A9B0C735-4B86-4620-AEE0-53AEB089C968
    weight: 100


services:
  - name: demo
    url: http://httpbin.org
    # url: http://host.docker.internal:6502
    routes:
      - name: my-route
        paths:
          - /
        strip_path: false
        filter_chains:
          - filters:
              - name: test_filter
                config: >-
                  { 
                    "upstream": "test_api",
                    "base_uri": "host.docker.internal:8080"
                  }
```

`test_filter` is invoking `dispatch_http_call` during `on_tick` like so:

```
        let headers = vec![
            (":method", method), // "POST"
            (":path", path), // "/v1/tap/batch"
            (":scheme", "http"),
            (":authority", &self.config.env.base_uri), // "host.docker.internal:8080"
            ("accept", "*/*"),
            ("content-type", "application/json"),
            ("content-length", &content_length),
        ];

        log::error!(
            "Dispatching {} upstream {} request to {}{} with body {}",
            &self.config.env.upstream,
            method,
            &self.config.env.base_uri,
            path,
            bodystr
        );

        match self.dispatch_http_call(
            &self.config.env.upstream, // "test_api"
            headers,
            Some(&body),
            trailers,
            timeout,
        ) {

```

This is what shows up in the logs:

```
[proxy-wasm]["test_filter" #0] root context resuming "on_tick" step in "background" phase
[proxy-wasm]["test_filter" #0] Dispatching test_api upstream POST request to host.docker.internal:8080/v1/tap/batch with body [{"request":"whatever"}]
[proxy-wasm]["test_filter" #0] setting next action: pwctx->action = "PAUSE" (pwctx: 000055D53ED874E0)
[proxy-wasm]["test_filter" #0] Dispatched request to /v1/tap/batch and got token 0
[proxy-wasm]["test_filter" #0] setting next action: pwctx->action = "CONTINUE" (pwctx: 000055D53ED874E0)
[proxy-wasm]["test_filter" #0] root context resuming "on_tick" step in "background" phase
...
[wasm] dispatch failed: tcp socket - resolver error: Host not found

```

I tried various hosts and ip addresses besides `host.docker.internal` and still get the last line, upstream is never being called. I also pass `--add-host host.docker.internal=host-gateway` to Docker. 

There is no diagnostic whatsoever to help with troubleshooting the issue. No documentation for how to properly use `dispatch_http_call` either.
